# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zap < Formula
  desc "Terminal launcher for AI coding CLIs"
  homepage "https://ryoshkenn.github.io/zap"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryoshkenn/zap/releases/download/v1.0.0/zap_1.0.0_macos_x86_64.tar.gz"
      sha256 "271c642c0f873f09bbb139614468b83c864fe9b1028288005f69b82aa7cc6fcc"

      define_method(:install) do
        bin.install "zap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryoshkenn/zap/releases/download/v1.0.0/zap_1.0.0_macos_arm64.tar.gz"
      sha256 "3b9beef8585a726338c694aebbaf87fa214d7dc4fabdd37357673e10b71278f6"

      define_method(:install) do
        bin.install "zap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryoshkenn/zap/releases/download/v1.0.0/zap_1.0.0_linux_x86_64.tar.gz"
      sha256 "3712fba269d15ab061933536007d4628cfff81cfadab6a597f62f005608b3164"
      define_method(:install) do
        bin.install "zap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryoshkenn/zap/releases/download/v1.0.0/zap_1.0.0_linux_arm64.tar.gz"
      sha256 "3680fa28293850a0da23bb2ced592d629a5162447a2f4b8723d9fa282d68a1fb"
      define_method(:install) do
        bin.install "zap"
      end
    end
  end

  test do
    system "#{bin}/zap --version"
  end
end
